#------------------------------------------------------------------
# Makefile for lab8
# Makes an executable binary file called GCD from source file
# GCD.c
#------------------------------------------------------------------

GCD: GCD.c
     gcc -o GCD GCD.c

clean:
     rm -f GCD

