#! /bin/bash
#----------------------------
# makeit
#----------------------------

echo "compiling Lawn.java"
javac Lawn.java >& Lawn-errs
echo "running Lawn.class"
java Lawn.java 
#echo "deleting the file Lawn.class"
#rm Lawn.class
